shell = "zsh"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
tag = "v0.7.1"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
tag = "0.36.0"
dir = "src"
apply = ["fpath"]
