include themes/catppuccin-mocha.conf

font_family JetBrainsMono Nerd Font
font_size 14.0
macos_titlebar_color dark
cursor_blink_interval 0
cursor_shape block

map ctrl+shift+f launch --type=overlay --stdin-source=@screen_scrollback fzf --no-sort --no-mouse --exact -i --tac

