#!/bin/bash


uuid=$(gsettings get org.gnome.Terminal.ProfilesList default | tr -d \')
profile=org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:${uuid}/

gsettings set org.gnome.desktop.peripherals.keyboard delay 250
gsettings set org.gnome.Terminal.Legacy.Settings default-show-menubar false

gsettings set ${profile} palette "['#4e4e4e', '#af5f5f', '#5f885f', '#af8760', '#5f87ae', '#875f87', '#5f8787', '#e4e4e4', '#3a3a3a', '#870100', '#005f00', '#d8865f', '#0087af', '#87025f', '#008787', '#eeeeee']"
gsettings set ${profile} background-color '#dadada'
gsettings set ${profile} foreground-color '#4e4e4e'
gsettings set ${profile} default-size-columns 97
gsettings set ${profile} default-size-rows 27
gsettings set ${profile} scrollbar-policy 'never'
gsettings set ${profile} use-theme-colors false

