#!/bin/bash


uuid=$(gsettings get org.gnome.Terminal.ProfilesList default | tr -d \')
profile=org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:${uuid}/

gsettings set org.gnome.desktop.peripherals.keyboard delay 250
gsettings set org.gnome.Terminal.Legacy.Settings default-show-menubar false

gsettings set ${profile} palette "['#000000', '#E06C75', '#98c379', '#d19a66', '#61aeee', '#c678dd', '#56b6c2', '#abb2bf', '#5c6370', '#e06c75', '#98c379', '#d19a66', '#62afee', '#c678dd', '#56b6c2', '#ffffff']"
gsettings set ${profile} background-color '#282c34'
gsettings set ${profile} foreground-color '#abb2bf'
gsettings set ${profile} default-size-columns 84
gsettings set ${profile} default-size-rows 18
gsettings set ${profile} scrollbar-policy 'never'
gsettings set ${profile} use-theme-colors false
gsettings set ${profile} use-theme-background false
