#!/bin/bash


uuid=$(gsettings get org.gnome.Terminal.ProfilesList default | tr -d \')
profile=org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:${uuid}/

gsettings set org.gnome.desktop.peripherals.keyboard delay 250
gsettings set org.gnome.Terminal.Legacy.Settings default-show-menubar false

gsettings set ${profile} palette "['#0f0e0d', '#845336', '#57553c', '#a17e3e', '#43454f', '#604848', '#5c6652', '#a18b62', '#383332', '#8c4f4a', '#898471', '#c8b491', '#65788f', '#755e4a', '#718062', '#bc9d66']"
gsettings set ${profile} background-color '#191716'
gsettings set ${profile} foreground-color '#daba8b'
gsettings set ${profile} default-size-columns 84
gsettings set ${profile} default-size-rows 18
gsettings set ${profile} scrollbar-policy 'never'
gsettings set ${profile} use-theme-colors false
