#! /bin/sh

bspc config border_width        2
bspc config window_gap         10

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config focused_border_color '#256980'

my_hostname=$(hostname)

if [[ "$my_hostname" == "shiki" ]]; then
    bspc monitor HDMI-0 -n L
    bspc monitor VGA-0 -n R
    bspc monitor R -s L
    bspc monitor L -d I II III IV V
    bspc monitor R -d VI VII VIII IX X
elif [[ "$my_hostname" == "cloud" ]]; then
    bspc monitor HDMI-0 -d I II III IV V VI VII VIII IX X
fi

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a mpv floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Steam desktop=^5
bspc rule -a dota2 desktop=^10

panel &
