#! /bin/sh

my_hostname=$(hostnamectl --static)

xsetroot -cursor_name left_ptr &
xset s off -dpms &
xset r rate 250 30 &
setxkbmap -layout us,ua -option caps:escape,grp:alt_shift_toggle,grp_led:caps &
feh --bg-fill "$HOME/Pictures/Wallpapers/qZpfcZH.png" &
sxhkd &

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

if [[ "$my_hostname" == "rain" ]]; then
    bspc monitor HDMI-0 -d I II III IV V VI VII VIII IX X
elif [[ "$my_hostname" == "shiki" ]]; then
    bspc monitor HDMI-0 -n L
    bspc monitor VGA-0 -n R
    bspc monitor R -s L
    bspc monitor L -d I II III IV V
    bspc monitor R -d VI VII VIII IX X
fi

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a chromium desktop=^2
bspc rule -a mplayer2 state=floating
bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Steam desktop=^5
bspc rule -a dota2 desktop=^10

panel &
