[tools]
usage = "latest"
fnox = "latest"
go = "latest"
rust = "latest"
uv = "latest"
python = "latest"
node = "latest"
aube = "latest"
lua = "latest"
"github:unhappychoice/gitlogue" = "latest"
kubectl = "latest"
krew = "latest"
terraform = "latest"
terragrunt = "latest"
tf-summarize = "latest"
packer = "latest"
aws = "latest"
"aqua:aws/session-manager-plugin" = "latest"
"pipx:mludvig/aws-ssm-tools" = "v2.2.1"
"npm:aws-cdk" = "latest"
"gitlab:gitlab-org/cli" = "latest"
"gitlab:dev-exp/other/tui-cli" = { version = "latest", api_url = "https://source.tui/api/v4" }
java = "corretto"
android-sdk = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []
minimum_release_age_excludes = ["fnox"]

[settings.python]
compile = false
uv_venv_create_args = ["--seed"]

[settings.node]
compile = false
