[tools]
usage = "latest"
aws = "latest"
"aqua:aws/session-manager-plugin" = "latest"
"pipx:mludvig/aws-ssm-tools" = "v2.2.1"
node = "latest"
uv = "latest"
python = "latest"
go = "latest"
rust = "latest"
java = "corretto"
terragrunt = "latest"
terraform = "latest"
android-sdk = "latest"
lua = "latest"
kubectl = "latest"
krew = "latest"
packer = "latest"
tf-summarize = "latest"
"github:caarlos0/svu" = "latest"
"github:unhappychoice/gitlogue" = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []

[settings.python]
compile = false
uv_venv_create_args = ["--seed"]

[settings.node]
compile = false
