# ~/.config/zsh/cache.zsh - tool output cache and completion setup, sourced by ~/.zshrc
#
# Init scripts and completions generated by tools are cached to files.
# Each file has a key: resolved binary path, binary mtime and arguments.
# A new shell regenerates a file when its key changes and deletes it when
# the tool is gone. All checks use zsh builtins, so a warm start forks nothing.
#
# Source this file before `mise activate`: it defines a compdef stub (see below).

zmodload -F zsh/stat b:zstat
zmodload -F zsh/files b:zf_ln b:zf_mv b:zf_rm b:zf_mkdir

typeset -g ZSH_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/zsh"
zf_mkdir -p "$ZSH_CACHE_DIR"/{init,keys,completions,mise-completions}

# mise hook-env registers completions and runs its own compinit when compdef
# is missing. This stub queues those calls until _zsh_compinit replays them.
typeset -ga _zsh_compdef_queue
compdef() { _zsh_compdef_queue+=("${(j: :)${(qq)@}}") }

typeset -ga _zsh_cache_used

#-------------------------------------------------
# Cache keys
#-------------------------------------------------

# Sets REPLY to the stored key of a cache entry
_zsh_key_read() {
  REPLY=
  [[ -r "$ZSH_CACHE_DIR/keys/$1" ]] && IFS= read -r REPLY <"$ZSH_CACHE_DIR/keys/$1"
  return 0
}

_zsh_key_write() {
  print -r -- "$2" >|"$ZSH_CACHE_DIR/keys/$1"
}

# Sets REPLY to the key of a command: <cmd> [args...]
_zsh_tool_key() {
  local bin=${commands[$1]:A}
  local -a mtime
  [[ -n $bin ]] && zstat -A mtime +mtime -- "$bin" || return 1
  REPLY="$bin:${mtime[1]}:${(j: :)@[2,-1]}"
}

#-------------------------------------------------
# Cached tool output
#-------------------------------------------------

# Writes the output of a command to a file atomically: <file> <cmd...>
_zsh_cache_write() {
  local file=$1 tmp="$ZSH_CACHE_DIR/keys/.tmp.$$"
  shift
  if "$@" >|"$tmp" 2>/dev/null && [[ -s $tmp ]]; then
    zf_mv -f "$tmp" "$file"
    return 0
  fi
  zf_rm -f "$tmp"
  return 1
}

# Keeps <file> equal to the output of <cmd...>: <file> <cmd...>
# The key comes from the binary of <cmd>. Returns 1 when the binary is
# missing or the command fails.
_zsh_cached() {
  local file=$1 name=${1:t}
  shift
  _zsh_cache_used+=("$file")
  if ! _zsh_tool_key "$@"; then
    zf_rm -f "$file" "$ZSH_CACHE_DIR/keys/$name"
    return 1
  fi
  local key=$REPLY
  _zsh_key_read "$name"
  [[ -s $file && $REPLY == "$key" ]] && return 0
  _zsh_cache_write "$file" "$@" && _zsh_key_write "$name" "$key"
}

# Caches the output of <cmd...> as an init script and sources it
_zsh_cached_source() {
  _zsh_cached "$ZSH_CACHE_DIR/init/$1.zsh" "$@" && source "$ZSH_CACHE_DIR/init/$1.zsh"
}

# Caches the output of <cmd...> as the completion function _<cmd>
_zsh_cached_comp() {
  _zsh_cached "$ZSH_CACHE_DIR/completions/_$1" "$@"
}

# Deletes cached files that no _zsh_cached call used in this startup.
# Call once, after the last _zsh_cached call.
_zsh_cache_prune() {
  local f
  for f in "$ZSH_CACHE_DIR"/{init,completions}/*(N); do
    ((${_zsh_cache_used[(Ie)$f]})) || zf_rm -f "$f" "$ZSH_CACHE_DIR/keys/${f:t}"
  done
  unset _zsh_cache_used
}

#-------------------------------------------------
# Completions shipped inside mise tool installs
#-------------------------------------------------

# Sets REPLY to the function name of a completion file, or returns 1
_zsh_comp_name() {
  local line
  IFS= read -r line <"$1" 2>/dev/null
  [[ $line == '#compdef '[^-]* ]] || return 1
  REPLY=${1:t}
  [[ $REPLY == _* && $REPLY != *.* ]] && return 0
  REPLY="_${${line#\#compdef }%% *}"
}

# Replaces the links in <dir> with links to <files...>
_zsh_comp_link() {
  local dir=$1 f tmp="$1/.tmp.$$"
  local -A want
  shift
  for f in "$@"; do
    _zsh_comp_name "$f" && want[$REPLY]=${f:A}
  done
  for f in ${(k)want}; do
    zf_ln -sfn "${want[$f]}" "$tmp" && zf_mv -f "$tmp" "$dir/$f"
  done
  for f in "$dir"/_*(N@); do
    ((${+want[${f:t}]})) || zf_rm -f "$f"
  done
}

# Links completion files of active mise tools into $ZSH_CACHE_DIR/mise-completions.
# The key is the set of resolved install dirs, so a tool install, upgrade or
# removal triggers a rescan.
_zsh_mise_comp_sync() {
  setopt localoptions extendedglob
  local base="${MISE_DATA_DIR:-$HOME/.local/share/mise}/installs" p rel
  local -aU roots
  for p in ${(M)path:#$base/*}; do
    rel=${p#$base/}
    roots+=("$base/${rel%%/*}/${${rel#*/}%%/*}")
  done
  roots=(${(o)roots:A})
  local key=${(j: :)roots}
  _zsh_key_read mise-completions
  [[ $REPLY == "$key" ]] && return 0
  local -a files=(
    $^roots/{completion,completions,autocomplete,complete}/(_*~*.*|*.zsh)(N-.)
    $^roots/*/{completion,completions,autocomplete,complete}/(_*~*.*|*.zsh)(N-.)
  )
  _zsh_comp_link "$ZSH_CACHE_DIR/mise-completions" "${files[@]}"
  _zsh_key_write mise-completions "$key"
}

#-------------------------------------------------
# compinit
#-------------------------------------------------

_zsh_compdef_replay() {
  local c
  for c in "${_zsh_compdef_queue[@]}"; do
    eval "compdef $c"
  done
  unset _zsh_compdef_queue
}

# Runs compinit and replays queued compdef calls. Call after fpath is final.
# Rebuilds the dump only when a directory in fpath changes. Adding or removing
# a completion file changes the mtime of its directory.
_zsh_compinit() {
  local dump="$ZSH_CACHE_DIR/.zcompdump"
  local -a dirs=(${^fpath}(N-/)) mtimes
  zstat -A mtimes +mtime -- $dirs
  local key="$ZSH_VERSION:${(j: :)dirs}:${(j: :)mtimes}"
  autoload -Uz compinit
  _zsh_key_read zcompdump
  if [[ -s $dump && $REPLY == "$key" ]]; then
    compinit -C -d "$dump"
  else
    compinit -i -d "$dump"
    zcompile -- "$dump"
    _zsh_key_write zcompdump "$key"
  fi
  _zsh_compdef_replay
}
