#!/bin/bash


uuid=$(gsettings get org.gnome.Terminal.ProfilesList default | tr -d \')
profile=org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:${uuid}/


gsettings set ${profile} palette "['#595370', '#ee8b37', '#f0ecff', '#ffcc99', '#a491fe', '#e69f59', '#c4b9ff', '#c3aeff', '#595370', '#f18d38', '#f0ecff', '#ffcc99', '#a491fe', '#e69f59', '#c4b9ff', '#c3aeff']"
gsettings set ${profile} background-color '#2a2734'
# gsettings set ${profile} background-color '#1e2327'
gsettings set ${profile} foreground-color '#9085b2'
gsettings set ${profile} default-size-columns 84
gsettings set ${profile} default-size-rows 18
gsettings set ${profile} scrollbar-policy 'never'
gsettings set ${profile} use-theme-colors false
gsettings set ${profile} cursor-blink-mode 'off'
