#!/bin/bash


uuid=$(gsettings get org.gnome.Terminal.ProfilesList default | tr -d \')
profile=org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:${uuid}/


gsettings set ${profile} palette "['#4e4e4e', '#d68787', '#5f865f', '#d8af5f', '#85add4', '#d7afaf', '#87afaf', '#d0d0d0', '#626262', '#d75f87', '#87af87', '#ffd787', '#add4fb', '#ffafaf', '#87d7d7', '#e4e4e4']"
gsettings set ${profile} background-color '#3a3a3a'
gsettings set ${profile} foreground-color '#d0d0d0'
gsettings set ${profile} default-size-columns 84
gsettings set ${profile} default-size-rows 18
gsettings set ${profile} scrollbar-policy 'never'
gsettings set ${profile} use-theme-colors false
gsettings set ${profile} cursor-blink-mode 'off'
