#!/bin/bash


uuid=$(gsettings get org.gnome.Terminal.ProfilesList default | tr -d \')
profile=org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:${uuid}/


gsettings set ${profile} palette "['#262626', '#d75f5f', '#afaf00', '#ffaf00', '#83adad', '#d485ad', '#85ad85', '#dab997', '#8a8a8a', '#d75f5f', '#afaf00', '#ffaf00', '#83adad', '#d485ad', '#85ad85', '#ebdbb2']"
gsettings set ${profile} background-color '#262626'
gsettings set ${profile} foreground-color '#dab997'
gsettings set ${profile} default-size-columns 84
gsettings set ${profile} default-size-rows 18
gsettings set ${profile} scrollbar-policy 'never'
gsettings set ${profile} use-theme-colors false
gsettings set ${profile} cursor-blink-mode 'off'
