#!/bin/bash


uuid=$(gsettings get org.gnome.Terminal.ProfilesList default | tr -d \')
profile=org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:${uuid}/


gsettings set ${profile} palette "['#33303b', '#87404f', '#4c9882', '#71949a', '#615772', '#783e57', '#554757', '#c0a79a', '#4f4b58', '#87404f', '#4c9882', '#71949a', '#615772', '#783e57', '#554757', '#c0a79a']"
gsettings set ${profile} background-color '#312e39'
gsettings set ${profile} foreground-color '#c0a79a'
gsettings set ${profile} default-size-columns 84
gsettings set ${profile} default-size-rows 18
gsettings set ${profile} scrollbar-policy 'never'
gsettings set ${profile} use-theme-colors false
gsettings set ${profile} cursor-blink-mode 'off'
