library: ~/.config/beets/library.db
ui:
    color: yes
plugins: fetchart embedart
import:
    move: yes
paths:
    default: $albumartist/$year - $album%aunique{}/$track $title
fetchart:
    cautious: true
