# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#E1E1DE"

# Main text color
theme[main_fg]="#73787D"

# Title color for boxes
theme[title]="#73787D"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#7E8FAF"

# Background color of selected item in processes box
theme[selected_bg]="#D4CDD4"

# Foreground color of selected item in processes box
theme[selected_fg]="#7E8FAF"

# Color of inactive/disabled text
theme[inactive_fg]="#AEAEA6"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#8E8A80"

# Background color of the percentage meters
theme[meter_bg]="#D8D8D2"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#577888"

# Cpu box outline color
theme[cpu_box]="#7880A5"

# Memory/disks box outline color
theme[mem_box]="#7E9579"

# Net up/down box outline color
theme[net_box]="#9E7E98"

# Processes box outline color
theme[proc_box]="#577888"

# Box divider line and small boxes line color
theme[div_line]="#AEAEA6"

# Temperature graph colors
theme[temp_start]="#7E9579"
theme[temp_mid]="#A7956A"
theme[temp_end]="#C27672"

# CPU graph colors
theme[cpu_start]="#7E9579"
theme[cpu_mid]="#A7956A"
theme[cpu_end]="#C27672"

# Mem/Disk free meter
theme[free_start]="#7E9579"
theme[free_mid]="#7E9579"
theme[free_end]="#7E9579"

# Mem/Disk cached meter
theme[cached_start]="#7880A5"
theme[cached_mid]="#7880A5"
theme[cached_end]="#7880A5"

# Mem/Disk available meter
theme[available_start]="#7B958E"
theme[available_mid]="#7B958E"
theme[available_end]="#7B958E"

# Mem/Disk used meter
theme[used_start]="#B28D77"
theme[used_mid]="#B28D77"
theme[used_end]="#B28D77"

# Download graph colors
theme[download_start]="#7880A5"
theme[download_mid]="#577888"
theme[download_end]="#577888"

# Upload graph colors
theme[upload_start]="#B28D77"
theme[upload_mid]="#C27672"
theme[upload_end]="#C27672"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#7E9579"
theme[process_mid]="#7B958E"
theme[process_end]="#577888"
