# import = ["~/.config/alacritty/themes/rose-pine/rose-pine.toml"]
import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]

[window]
dimensions = { columns = 110, lines = 26 }
decorations_theme_variant = "Dark"
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"

[scrolling]
history = 50000

[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 14.0

[env]
TERM = "xterm-256color"