plugins:
  - fetchart
  - embedart
  - convert
  - fromfilename

ui:
  color: yes

import:
  move: yes
  group_albums: yes

paths:
  default: $albumartist/$year - $album%aunique{}/$track $title

fetchart:
  cautious: true
  maxwidth: 600

embedart:
  maxwidth: 600

embedart:
  remove_art_file: true

convert:
  auto: yes
  never_convert_lossy_files: yes
  formats:
    mp3: ffmpeg -i $source -y -vn -aq 0 $dest
