plugins: fetchart embedart convert

ui:
  color: yes

import:
  move: yes

paths:
  default: $albumartist/$year - $album%aunique{}/$track $title

fetchart:
  cautious: true

convert:
  auto: yes
  never_convert_lossy_files: yes
  formats:
    mp3: ffmpeg -i $source -y -vn -aq 0 $dest
