plugins:
  - fetchart
  - embedart
  - convert
  - fromfilename
  - discogs

ui:
  color: yes

import:
  move: yes
  group_albums: yes

paths:
  default: $albumartist/$year - $album%aunique{}/$track $title

fetchart:
  cautious: yes
  maxwidth: 600

embedart:
  maxwidth: 600

embedart:
  remove_art_file: yes

convert:
  auto: yes
  never_convert_lossy_files: yes
  formats:
    mp3: ffmpeg -i $source -y -vn -q:a 0 $dest

discogs:
  user_token: cYmqjGVgvLvPcUxsEUDDSNBSZVfmzAjGZdqARIHw
